name: Unit Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies (EmailLib)
        run: dotnet restore Paubox_Csharp/EmailLib/EmailLib.csproj

      - name: Build (EmailLib)
        run: dotnet build Paubox_Csharp/EmailLib/EmailLib.csproj --no-restore --configuration Release

      - name: Restore dependencies (UnitTestProject)
        run: dotnet restore Paubox_Csharp/UnitTestProject/UnitTestProject.csproj

      - name: Build (UnitTestProject)
        run: dotnet build Paubox_Csharp/UnitTestProject/UnitTestProject.csproj --no-restore --configuration Release

      - name: Test
        run: dotnet test Paubox_Csharp/UnitTestProject/UnitTestProject.csproj --configuration Release --verbosity normal
